# This is a basic workflow to help you get started with Actions

name: osx-ubuntu-build-android

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install and start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 3.4

    - name: Install miniconda
      shell: bash -l {0}
      run: source setup/setup_conda.sh

    - name: Setup the emission environment for testing
      shell: bash -l {0}
      run: source setup/setup.sh

    - name: Switch to emission and run the tests
      shell: bash -l {0}
      run: |
        source activate emission
        ./runAllTests.sh

    - name: Teardown the test environment
      shell: bash -l {0}
      run: source setup/teardown_tests.sh
